*** Begin Patch
*** 
*** src/skill-forge/distiller.ts
*** 
***  **105,111 ****
***  const laneSpecific = laneSpecificSection(candidate);
***  return [
***    `#${candidate.lane === "tool-shape" ? "Repeated Workflow" : candidate.lane === "error-recovery" ? "Recovery Workflow" : "User-Tagged Workflow"}`,
***    "",
***    LLM_PROSE_TODO_MARKER,
***    "",
***    "## Overview",
***    "",
***    "Heuristic draft generated by skill-forge from captured session trajectories.",
***    "Replace this body with LLM-distilled prose once the distillation provider is wired.",
***    "",
***    "## Tool sequence",
***    "",
***    sequenceBlock,
***    "",
***    laneSpecific,
***    "",
***    "## Provenance",
***    "",
***    `- Lane: \`${candidate.lane}\``,
***    `- Candidate id: \`${candidate.candidateId}\``,
***    "",
***  ].join("\n");
*** --- 
***  const laneSpecific = laneSpecificSection(candidate);
***  const processVsOutcomeSection = candidate.processVsOutcome ? formatProcessVsOutcome(candidate.processVsOutcome) : "";
***  return [
***    `#${candidate.lane === "tool-shape" ? "Repeated Workflow" : candidate.lane === "error-recovery" ? "Recovery Workflow" : "User-Tagged Workflow"}`,
***    "",
***    LLM_PROSE_TODO_MARKER,
***    "",
***    "## Overview",
***    "",
***    "Heuristic draft generated by skill-forge from captured session trajectories.",
***    "Replace this body with LLM-distilled prose once the distillation provider is wired.",
***    "",
***    "## Tool sequence",
***    "",
***    sequenceBlock,
***    "",
***    laneSpecific,
***    "",
***    processVsOutcomeSection,
***    "",
***    "## Provenance",
***    "",
***    `- Lane: \`${candidate.lane}\``,
***    `- Candidate id: \`${candidate.candidateId}\``,
***    "",
***  ].join("\n");
*** 
*** *** End Patch ***