import fsp from "node:fs/promises";
import path from "node:path";
import type { Candidate } from "./detector.js";
import { resolveSkillForgeStagedSkillDir } from "./paths.js";

const MAX_SKILL_NAME_LENGTH = 64;
const FORGE_NAME_PREFIX = "forge-";
const LLM_PROSE_TODO_MARKER =
  "<!-- TODO(skill-forge): replace heuristic body with LLM-distilled prose once distillation provider is wired. -->";

export const DISTILLER_PROSE_TODO = LLM_PROSE_TODO_MARKER;

export function normalizeSkillName(input: string): string {
  const lower = input.trim().toLowerCase();
  const dashed = lower.replace(/[^a-z0-9]+/gu, "-").replace(/^-+|-+$/gu, "");
  const collapsed = dashed.replace(/-{2,}/gu, "-");
  if (collapsed.length === 0) {
    return "unnamed";
  }
  return collapsed.length > MAX_SKILL_NAME_LENGTH
    ? collapsed.slice(0, MAX_SKILL_NAME_LENGTH)
    : collapsed;
}

function truncateForName(input: string, max: number): string {
  return input.length > max ? input.slice(0, max) : input;
}

export function skillNameForCandidate(candidate: Candidate): string {
  if (candidate.lane === "tool-shape") {
    const shapeHint = truncateForName(candidate.toolSequence.slice(0, 2).join("-"), 24);
    return normalizeSkillName(
      `${FORGE_NAME_PREFIX}rep-${shapeHint || candidate.toolShapeHash.slice(0, 8)}-${candidate.toolShapeHash.slice(0, 6)}`,
    );
  }
  if (candidate.lane === "error-recovery") {
    return normalizeSkillName(
      `${FORGE_NAME_PREFIX}recover-${candidate.failingTool}-via-${candidate.recoveringTool}-${candidate.candidateId.slice(0, 6)}`,
    );
  }
  return normalizeSkillName(`${FORGE_NAME_PREFIX}explicit-${candidate.candidateId.slice(0, 8)}`);
}

function descriptionForCandidate(candidate: Candidate, toolSequence: string[]): string {
  const tools = toolSequence.slice(0, 4).join(", ") || "(no tool calls)";
  if (candidate.lane === "tool-shape") {
    return `Workflow seen ${candidate.occurrences} times across captured sessions: ${tools}. Use when the same multi-step sequence keeps repeating across tasks.`;
  }
  if (candidate.lane === "error-recovery") {
    return `Recovery workflow: when ${candidate.failingTool} fails, recover with ${candidate.recoveringTool}. Use when ${candidate.failingTool} returns an error that ${candidate.recoveringTool} resolves.`;
  }
  return `User-tagged workflow (${candidate.matchedPhrase}): ${tools}. Use when the user explicitly asks for the workflow excerpted in the source capture.`;
}

function laneSpecificSection(candidate: Candidate): string {
  if (candidate.lane === "tool-shape") {
    return [
      "## When this triggers",
      "",
      `Detected from ${candidate.occurrences} captured sessions that all executed the same tool sequence.`,
      "",
      `Source captures:`,
      "",
      ...candidate.captureDirs.map((dir) => `- \`${dir}\``),
    ].join("\n");
  }
  if (candidate.lane === "error-recovery") {
    return [
      "## When this triggers",
      "",
      `\`${candidate.failingTool}\` failed in the source capture; recovery succeeded by calling \`${candidate.recoveringTool}\` (full recovery path: ${candidate.toolSequence.map((t) => `\`${t}\``).join(" → ")}).`,
      "",
      `Source capture: \`${candidate.captureDir}\``,
      "",
      `**Heuristic:** ${candidate.rationale}.`,
    ].join("\n");
  }
  return [
    "## When this triggers",
    "",
    `User asked to crystallize this workflow via the phrase \`${candidate.matchedPhrase}\`.`,
    "",
    `Prompt excerpt:`,
    "",
    "```",
    candidate.promptExcerpt,
    "```",
    "",
    `Source capture: \`${candidate.captureDir}\``,
  ].join("\n");
}

function bodyForCandidate(candidate: Candidate, toolSequence: string[]): string {
  const sequenceBlock =
    toolSequence.length > 0
      ? toolSequence.map((tool, index) => `${index + 1}. \`${tool}\``).join("\n")
      : "_no tool calls captured_";
  const laneSpecific = laneSpecificSection(candidate);
  return [
    `# ${candidate.lane === "tool-shape" ? "Repeated Workflow" : candidate.lane === "error-recovery" ? "Recovery Workflow" : "User-Tagged Workflow"}`,
    "",
    LLM_PROSE_TODO_MARKER,
    "",
    "## Overview",
    "",
    "Heuristic draft generated by skill-forge from captured session trajectories.",
    "Replace this body with LLM-distilled prose once the distillation provider is wired.",
    "",
    "## Tool sequence",
    "",
    sequenceBlock,
    "",
    laneSpecific,
    "",
    "## Provenance",
    "",
    `- Lane: \`${candidate.lane}\``,
    `- Candidate id: \`${candidate.candidateId}\``,
    "",
  ].join("\n");
}

export type DraftedSkill = {
  name: string;
  skillDir: string;
  skillMdPath: string;
  description: string;
};

export async function distillCandidateToStaging(params: {
  candidate: Candidate;
  env?: NodeJS.ProcessEnv;
}): Promise<DraftedSkill> {
  const env = params.env ?? process.env;
  const candidate = params.candidate;
  const name = skillNameForCandidate(candidate);
  const toolSequence = candidate.toolSequence;
  const description = descriptionForCandidate(candidate, toolSequence);
  const body = bodyForCandidate(candidate, toolSequence);
  const skillDir = resolveSkillForgeStagedSkillDir({ name, env });
  await fsp.mkdir(skillDir, { recursive: true });
  const skillMdPath = path.join(skillDir, "SKILL.md");
  const frontmatter = `---\nname: ${name}\ndescription: ${escapeYamlScalar(description)}\n---\n\n`;
  await fsp.writeFile(skillMdPath, `${frontmatter}${body}`, "utf8");
  return { name, skillDir, skillMdPath, description };
}

function escapeYamlScalar(value: string): string {
  if (value.includes("\n") || /^[?\-*&!|>%@`]/u.test(value) || /:\s/u.test(value)) {
    return `"${value.replace(/\\/gu, "\\\\").replace(/"/gu, '\\"')}"`;
  }
  return value;
}
