// Builds transcript summaries and normalized transcript metadata.
import {
  normalizeStringEntries,
  normalizeUniqueStringEntries,
} from "@openclaw/normalization-core/string-normalization";
import { sanitizeTerminalText } from "../../packages/terminal-core/src/safe-text.js";
import type { OpenClawConfig } from "../config/types.openclaw.js";
import type { TranscriptSessionDescriptor, TranscriptUtterance } from "./provider-types.js";

/**
 * Lightweight transcript summarization and markdown rendering.
 *
 * This is a deterministic heuristic summary used for captured/imported
 * transcripts when no model-backed summarizer is involved.
 */
/** Summary artifact written alongside transcript sessions. */
export type TranscriptsSummary = {
  sessionId: string;
  title: string;
  generatedAt: string;
  overview: string;
  participants: string[];
  source: "model" | "heuristic";
  model?: string;
  transcript: string[];
  decisions: string[];
  actionItems: string[];
  risks: string[];
  utteranceCount: number;
  /** Pre-computed embedding vector for semantic search across sessions.
   * Generated by generateSummaryEmbedding() and consumed by memory_search.
   * Absent for summaries written before this feature was added. */
  embedding?: number[];
};

const ACTION_PATTERNS =
  /\b(todo|action|follow up|follow-up|assign|owner|next step|ship|fix|send|schedule)\b/i;
const DECISION_PATTERNS = /\b(decided|decision|we will|we'll|agreed|approved|go with|ship it)\b/i;
const RISK_PATTERNS =
  /\b(risk|blocked|blocker|concern|issue|problem|unknown|deadline|privacy|security)\b/i;

function firstSentences(utterances: TranscriptUtterance[], limit: number): string {
  const text = normalizeStringEntries(utterances.map((utterance) => utterance.text)).join(" ");
  const sentences = text.match(/[^.!?]+[.!?]?/g) ?? [];
  return normalizeStringEntries(sentences.slice(0, limit)).join(" ");
}

function collectMatches(utterances: TranscriptUtterance[], pattern: RegExp): string[] {
  return utterances
    .filter((utterance) => pattern.test(utterance.text))
    .map(formatSpeakerLine)
    .filter(Boolean)
    .slice(0, 12);
}

function sanitizeUtterance(utterance: TranscriptUtterance): TranscriptUtterance {
  const sanitized: TranscriptUtterance = {
    ...utterance,
    text: sanitizeTerminalText(utterance.text),
  };
  if (utterance.speaker) {
    sanitized.speaker = {
      ...utterance.speaker,
      label: sanitizeTerminalText(utterance.speaker.label),
    };
  }
  return sanitized;
}

function formatSpeakerLine(utterance: TranscriptUtterance): string {
  const text = utterance.text.trim();
  if (!text) {
    return "";
  }
  const speaker = utterance.speaker?.label?.trim();
  return speaker ? `${speaker}: ${text}` : text;
}

function formatTranscript(utterances: TranscriptUtterance[]): string[] {
  return utterances.map(formatSpeakerLine).filter(Boolean);
}

/** Build a deterministic summary from transcript utterances. */
export function summarizeTranscripts(params: {
  session: TranscriptSessionDescriptor;
  utterances: TranscriptUtterance[];
}): TranscriptsSummary {
  const title = sanitizeTerminalText(params.session.title ?? "").trim() || "Transcripts";
  const utterances = params.utterances.map(sanitizeUtterance);
  const overview = firstSentences(utterances, 4) || "No transcript captured yet.";
  return {
    sessionId: params.session.sessionId,
    title,
    generatedAt: new Date().toISOString(),
    overview,
    participants: normalizeUniqueStringEntries(
      utterances.map((utterance) => utterance.speaker?.label ?? ""),
    ),
    source: "heuristic",
    transcript: formatTranscript(utterances),
    decisions: collectMatches(utterances, DECISION_PATTERNS),
    actionItems: collectMatches(utterances, ACTION_PATTERNS),
    risks: collectMatches(utterances, RISK_PATTERNS),
    utteranceCount: params.utterances.length,
  };
}

function renderList(items: string[]): string {
  return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "- None captured";
}

/** Render a transcript summary as markdown for local artifacts. */
export function renderTranscriptsMarkdown(summary: TranscriptsSummary): string {
  return [
    `# ${summary.title}`,
    "",
    `Generated: ${summary.generatedAt}`,
    `Session: ${sanitizeTerminalText(summary.sessionId)}`,
    "",
    "## Overview",
    summary.overview,
    "",
    "## Participants",
    // Persisted summaries from before participant metadata remain renderable.
    renderList(summary.participants ?? []),
    "",
    "## Decisions",
    renderList(summary.decisions),
    "",
    "## Action Items",
    renderList(summary.actionItems),
    "",
    "## Risks",
    renderList(summary.risks),
    "",
    // Keep notes ahead of the transcript for bounded readers such as tool show.
    "## Transcript",
    renderList(summary.transcript),
    "",
    `Transcript utterances: ${summary.utteranceCount}`,
  ].join("\n");
}

/**
 * Build the text input for embedding from a summary.
 *
 * Concatenates overview, decisions, action items, and risks into a single
 * string that captures the semantic content of the session. The transcript
 * array is intentionally excluded — it's typically too long and adds noise.
 */
export function buildSummaryEmbeddingText(summary: TranscriptsSummary): string {
  const parts: string[] = [];
  if (summary.overview) {
    parts.push(summary.overview);
  }
  if (summary.decisions.length > 0) {
    parts.push("Decisions:");
    parts.push(...summary.decisions);
  }
  if (summary.actionItems.length > 0) {
    parts.push("Action Items:");
    parts.push(...summary.actionItems);
  }
  if (summary.risks.length > 0) {
    parts.push("Risks:");
    parts.push(...summary.risks);
  }
  return parts.join("\n");
}

/**
 * Generate an embedding vector for a transcript summary.
 *
 * Uses the core OpenClaw embedding provider ("openai" adapter) to embed
 * the summary's overview + decisions + actions + risks. The resulting vector
 * is stored in `summary.embedding` and indexed for semantic search via
 * `memory_search` with `corpus=sessions`.
 *
 * Throws if no embedding provider is configured.
 * Returns the embedding vector (also mutates summary.embedding in place).
 */
export async function generateSummaryEmbedding(params: {
  summary: TranscriptsSummary;
  cfg: OpenClawConfig;
}): Promise<number[]> {
  const { getMemoryEmbeddingProvider } =
    await import("../plugins/memory-embedding-provider-runtime.js");
  const adapter = getMemoryEmbeddingProvider("openai", params.cfg);
  if (!adapter) {
    throw new Error("No embedding provider configured");
  }
  const createResult = await adapter.create({
    config: params.cfg,
    model: adapter.defaultModel ?? "",
  });
  const provider = createResult.provider;
  if (!provider) {
    throw new Error("Failed to create embedding provider instance");
  }
  const text = buildSummaryEmbeddingText(params.summary);
  const vectors = await provider.embedBatch([text]);
  const embedding = vectors[0];
  if (embedding === undefined) {
    throw new Error("Embedding provider returned no vector for summary");
  }
  // Mutate summary in place so callers that already hold a reference
  // get the embedding without reassignment.
  params.summary.embedding = embedding;
  return embedding;
}
